// Portada
// TODO: Cambiar placeholders.
// TODO: Cambiar estilado, añadir negritas, centrar, etc. Revisar Anexo A1 de la Guía Informe TG.
Universidad Católica Andrés Bello
Facultad de Ingeniería
Escuela de Ingeniería Informática

Ambiente de Programación Tangible con Realidad Aumentada Espacial Orientado a Niños entre 6 y 9 años

Trabajo de Grado
presentado ante la
UNIVERSIDAD CATÓLICA ANDRÉS BELLO
como parte de los requisitos para optar al título de
Ingeniero en Informática
// TODO: formato tabla, izquierda realizado por, derecha nombres
Realizado por | Arzolay Rodríguez, Eduardo Javier Isidoro
| Vásquez Paniagua, Luis Daniel
Tutor Académico | Lárez Mata, Jesús José
Fecha | Mes, Año

// Capítulo I
= Capítulo I. El Problema
// TODO: Usar referencias y citas de Typst en vez de manuales.
// TODO: Arreglar estilado.
== Planteamiento del Problema
Papert (1980) predijo el auge de las computadoras en la educación, planteando que los niños deberían aprender a programar tal y como es aprender francés viviendo en Francia en vez de aprenderlo mediante las clases de lenguas extranjeras en las aulas del colegio; es decir, mediante la interacción directa con las computadoras, un enfoque en que el niño use y experimente con la computadora para aprender, en vez de que la computadora le enseñe al niño. También hace énfasis en que la simple presencia de las computadoras cambiaría y moldearía una nueva forma de enseñar y aprender, inimaginable para la sociedad de aquel momento. Papert fue un visionario, pues lo que él defendía se hizo realidad en partes, con una creciente demanda de la competencia del pensamiento computacional, término que no usó Papert sino Wing (2006) para referirse a la forma de pensar de los científicos de computación; pero con retos que enfrentar.
Quien acuñó el término de pensamiento computacional, Wing (2006), lo describe como una habilidad que todos deberían aprender y usar, no solo los científicos en computación. Defiende que debería de añadirse a la educación de los niños, al mismo nivel que las 3R (lectura, escritura y aritmética), por los usos que tiene, no solo al aprender a programar, sino en la descomposición y solución de problemas, la creación de modelos, el análisis de datos, la abstracción. Añade que su utilidad en otras disciplinas ya es visible, notándose en cómo el aprendizaje automático ha transformado a la estadística, el reciente interés de los científicos de computación en la biología, o la computación cuántica y su efecto en la física. El sueño de Papert, que todos tuvieran una computadora, se convirtió en lo que se conoce hoy como computación ubicua; Wing, por su parte, sueña que el pensamiento computacional sea igual de omnipresente, y propone que el primer paso es que deje de ser exclusivo de los científicos de computación, que se enseñe a los estudiantes preuniversitarios.
En la actualidad, la presencia de computadoras, tabletas, teléfonos, televisores y relojes inteligentes, y demás dispositivos con pantalla; resulta en que los seres humanos están expuestos a las pantallas durante todo el día, en períodos de tiempo extensos incluso en ambientes dedicados a la enseñanza y el aprendizaje, como los colegios y universidades; causando la preocupación generalizada por los efectos a corto y largo plazo de esto, especialmente en los niños. Council on Communications and Media et al. (2016), en representación de la Academia Americana de Pediatría, sostienen que el uso de pantallas en niños de 2 a 5 años no debe sobrepasar una hora al día, dividida en periodos cortos con descansos frecuentes. J. Duarte (comunicación personal, 28 de febrero de 2025) respalda a la AAP, añadiendo que los periodos continuos de exposición han de ser de 15 minutos como máximo, condicionando el uso de herramientas como Scratch para el desarrollo del pensamiento computacional durante sus sesiones de clase, y recurriendo en su lugar a herramientas tangibles, como el juego de mesa Mouse Mania, que presentan limitaciones para la enseñanza de conceptos avanzados, como los bucles y condicionales, y dificultan fomentar el aprendizaje colaborativo y la socialización entre niños.
La primera aproximación al uso de herramientas tangibles para la enseñanza de conceptos de programación a niños vino de parte de Radia Perlman, pionera en el área de las interfaces de usuario tangibles (Morgado et al., 2006), quien desarrolló entre 1974 y 1976 un lenguaje de programación tangible de sistemas, llamado TORTIS, con la finalidad de que los niños pudieran adquirir las competencias que traía el aprender lenguajes de programación completos al interactuar con objetos físicos. Este lenguaje consistía en controlar una pequeña “tortuga” (un disco equipado con una luz, una bocina y un lápiz, este último encargado de dibujar el resultado de la ejecución del programa) mediante uno de dos componentes: una serie de cajas de botones con acciones, o una “máquina tragacartas” con cartas de plástico. La razón detrás de la creación de dos componentes para interactuar con el lenguaje es, interpretando las palabras de Perlman, que con las cajas de botones los niños pensaban que el programa era el dibujo resultante, en vez del conjunto de comandos que ejecutaban con los botones; mientras que, con la máquina tragafichas, que construyó para solucionar el problema de las cajas, era difícil que lo niños entendieran que cada carta estaba asociada a un comando porque, para la ejecución de cada una, se debía buscar la carta, insertarla en una ranura de la máquina y presionar un botón. Incluso con estos problemas, Perlman llegó a una nueva aproximación para la enseñanza de conceptos de programación para los niños.
Un ejemplo más conocido de programación tangible es el caso de AlgoBlock (Suzuki y Kato, 1993), un lenguaje de programación tangible inspirado en Logo que consiste en unir una serie de bloques físicos para formar un programa que controla un submarino mostrado en una pantalla. Igual que las cartas en el segundo componente de TORTIS, cada bloque representa un comando, y algunos bloques representan estructuras de control condicionales y de bucle. Lo interesante de AlgoBlock son los principios que siguieron sus autores en su desarrollo: facilidad de uso, acceso simultáneo, monitoreo mutuo y pase del turno mediante gestos; los cuales incitan la conversación y la colaboración entre los participantes. Aunque los autores no mencionan alguna deficiencia en AlgoBlock tras ponerlo a prueba, sí hacen énfasis en que este solo representa el primer paso en la identificación de los principios para el diseño de ambientes de aprendizaje colaborativo.
La idea detrás de la programación tangible es llevada más allá por Zapata-Ros (2019), quien habla sobre el pensamiento computacional desenchufado, que ayuda a que los niños adquieran las competencias relacionadas al pensamiento computacional en las etapas de su vida en que más la necesiten, como durante los estudios secundarios o la universidad, basándose en los principios fundamentales de la instrucción propuestos por Merrill (2002), especialmente en el principio de activación. Zapata-Ros describe al pensamiento computacional desenchufado como actividades que fomenten en los niños una serie de habilidades que, tras ser evocadas en ciclos superiores, favorezcan el desarrollo del pensamiento computacional, ejemplos de estas son el uso de fichas, juegos en el salón de clase o en el patio, juguetes, aquellas que se suelen hacer sin el uso de pantallas ni computadoras. Además, sugiere actividades ya existentes con estas características y la forma de usarlas para promover el pensamiento computacional.
Aparte del pensamiento computacional desenchufado, la realidad aumentada espacial también presenta similitudes con la programación tangible, al permitir la superposición del mundo real con el virtual (Park et al., 2015), de cierta manera siendo la evolución de TORTIS y AlgoBlock; y, al igual que el pensamiento computacional desenchufado, se ha utilizado la realidad aumentada espacial para fomentar el desarrollo del pensamiento computacional en niños. Billinghurst y Duenser (2012) evaluaron el uso de realidad aumentada espacial en aulas de clase, específicamente en forma de libros aumentados (libros impresos en los que algunas de sus páginas tienen imágenes virtuales superpuestas) y aplicaciones móviles de realidad aumentada, siendo los resultados recopilados del uso de los libros aumentados los de mayor interés para esta investigación, destacando la utilidad en la enseñanza de conceptos espaciales al proveer una interacción intuitiva, atractiva y natural de los temas estudiados; apoyando en la retención de contenidos que se desenvuelven en secciones de realidad aumentada, permitiendo que niños con dificultades en la comprensión de textos de aprendizaje tengan la opción de interactuar con el contenido para aprender; y en el desarrollo del pensamiento computacional al hacer uso de herramientas de construcción de escenas de realidad aumentada espacial diseñadas para niños, quienes se inspiran en hacer sus propias escenas tras ver y experimentar con las de los libros aumentados. Además, como los libros en sí contienen secciones físicas intercaladas con secciones de realidad aumentada, se reducía el tiempo de uso de pantallas.
Pasando a Venezuela, Barrios (2025) de la Universidad Católica Andrés Bello (UCAB) presentó un entorno de realidad aumentada espacial que consiste en una mesa interactiva táctil, la cual permite el desarrollo de juegos sociales entre niños de educación preescolar y básica que promueven la colaboración y socialización. Con base en lo expuesto previamente, se ve la oportunidad de extender el entorno hecho por Barrios incluyendo un módulo de programación tangible, aprovechando el enfoque en juegos sociales para fomentar la colaboración, la socialización, el trabajo en equipo y el pensamiento computacional.
En este contexto, se propone desarrollar un ambiente de programación tangible con realidad aumentada espacial basado en los referentes mencionados, con la finalidad de promover el desarrollo significativo del pensamiento computacional desde edades tempranas, mediante un enfoque que promueva el aprendizaje colaborativo y un desarrollo integral que vaya más allá del cognitivo.

=== Objetivo General
Desarrollar un ambiente de programación tangible con realidad aumentada espacial orientado a niños entre 6 y 9 años.

=== Objetivos Específicos
+ Analizar el uso de programación tangible en entornos de realidad aumentada, a fin de caracterizar el ambiente a desarrollar.
+ Diseñar un ambiente de programación tangible con realidad aumentada espacial orientado a niños entre 6 y 9 años, en función del análisis realizado.
+ Construir un ambiente de programación tangible con realidad aumentada espacial orientado a niños entre 6 y 9 años, en base al diseño realizado.
+ Validar el ambiente de programación tangible con realidad aumentada espacial orientado a niños entre 6 y 9 años construido.
+ Realizar la documentación formal del ambiente de programación tangible con realidad aumentada espacial orientado a niños entre 6 y 9 años construido.

== Alcance
El presente trabajo tendrá como objetivo desarrollar un ambiente de programación tangible para fomentar el desarrollo del pensamiento computacional en niños entre 6 y 9 años de edad. Este estará orientado a fomentar el desarrollo del pensamiento computacional de los niños, considerando aspectos esenciales como el aprendizaje colaborativo, la socialización y la inclusividad.
En primer lugar, se llevará a cabo una etapa de revisión de conceptos para obtener detalles sobre el pensamiento computacional y su desarrollo en edades tempranas. A continuación, se realizará un análisis exhaustivo para comprender la aplicación de la programación tangible en entornos de realidad aumentada, con el fin de fomentar el pensamiento computacional.
Posteriormente, se procederá al diseño y desarrollo del entorno, que incluye dos aspectos: la construcción del hardware, que funcionará como interfaz de interacción humano-computador, y el desarrollo del software, encargado de procesar la información recibida a través del hardware. Adicionalmente, se propondrá un protocolo de pruebas que se aplicará durante la validación posterior a la construcción del entorno.
Finalmente, se elaborará la documentación correspondiente, incluyendo el manual del sistema y el manual de usuario.

== Limitaciones
=== Dificultades Asociadas a Nuevas Tecnologías
Podrían surgir inconvenientes durante el desarrollo y construcción del entorno debido a la falta de experiencia en realidad aumentada espacial.

=== Problemas Asociados a los Componentes Utilizados
Es posible que los componentes necesarios no sean de fácil acceso, especialmente el sensor Kinect, que actualmente no se comercializa con frecuencia. Además, pueden resultar costosos.
Para solucionar esto, los autores proveerán su propio Kinect, y se tomarán previsiones con respecto a los componentes faltantes.

== Justificación
Este trabajo de investigación apoyaría al desarrollo del pensamiento computacional, el aprendizaje colaborativo y la socialización entre los niños, fomentando la futura activación de estas competencias en su crecimiento personal, académico y profesional, y convirtiéndose en una herramienta útil y una gran alternativa para educadores conscientes en que los niños deben aprender sobre el mundo virtual sin sacrificar el mundo físico, con el añadido de combinar ambos mundos en una experiencia única.
=== Aporte Principal
El uso del ambiente de programación tangible permitiría que los niños aprendan de forma lúdica, creando experiencias significativas para el aprendizaje del pensamiento computacional a través de la manipulación de objetos físicos, reflejada en la visión por computador. Además, promovería el aprendizaje colaborativo, ayudándoles a desarrollar el pensamiento computacional.
=== Innovación
Se presentará una propuesta que permitiría a los niños acceder a un ambiente de aprendizaje interactivo para aprender a programar con componentes tanto físicos como digitales. Este enfoque equilibraría el uso de pantallas y las técnicas tradicionales de aprendizaje mediante la utilización de elementos físicos y digitales.
=== Beneficiarios
==== Niños entre 6 y 9 años de edad.
Fomentaría el desarrollo del pensamiento computacional en los niños desde edades tempranas, lo cual podría influir positivamente en su rendimiento académico y en su habilidad para resolver problemas lógicos.
==== Profesores de primeros grados de educación básica.
Contarían con una herramienta útil que facilitaría el proceso de enseñanza-aprendizaje a niños mediante juegos interactivos.
=== Impacto en los Objetivos de Desarrollo Sostenible
Esta investigación tendría un impacto significativo en el Objetivo 4 (Educación de calidad) de los Objetivos de Desarrollo Sostenible, especialmente en las Metas 4.4 y 4.6:
==== Meta 4.4.
Aumentaría el número de jóvenes y adultos con competencias necesarias para acceder al empleo, fomentando desde edades tempranas el desarrollo del pensamiento lógico y computacional.
==== Meta 4.6.
Promovería conocimientos básicos de aritmética en adultos, fomentando el aprendizaje desde la infancia a través de juegos interactivos.
