#* created_at and updated_at fields are omitted for brevity, but assumed to be present in all tables as timestamps with NOT NULL constraints.
#TODO: check commented validations with business
#* Validations that can't be easily represented: legal_id is unique in natural_persons and legal_persons, whereas the group (legal_id, legal_person_id, role) is unique in contact_persons
#* NULL in constraint: is nullable
vars: {
  d2-config: {
    layout-engine: tala
    sketch: true
  }
}

workspaces: {
  shape: sql_table
  id: int {constraint: primary_key}
}

teamspaces: {
  shape: sql_table
  id: int {constraint: primary_key}
  workspace_id: int {constraint: foreign_key}
}

teamspaces.workspace_id -> workspaces.id

users: {
  shape: sql_table
  id: int {constraint: primary_key}
  type: text # 'admin', 'operator', 'director', 'manager' or 'seller'
}

admins: {
  shape: sql_table
  id: int {constraint: [primary_key; foreign_key]}
}

admins.id -> users.id

operators: {
  shape: sql_table
  id: int {constraint: [primary_key; foreign_key]}
}

operators.id -> users.id

directors: {
  shape: sql_table
  id: int {constraint: [primary_key; foreign_key]}
}

directors.id -> users.id

managers: {
  shape: sql_table
  id: int {constraint: [primary_key; foreign_key]}
}

managers.id -> users.id

sellers: {
  shape: sql_table
  id: int {constraint: [primary_key; foreign_key]}
}

sellers.id -> users.id

products {
  shape: sql_table
  id: int {constraint: primary_key}
}

states: {
  shape: sql_table
  id: int {constraint: primary_key}
  name: text
}

cities: {
  shape: sql_table
  id: int {constraint: primary_key}
  name: text
  state_id: int {constraint: foreign_key}
}

cities.state_id -> states.id

#TODO: check contacts schema for duplication -> a person may be in multiple legal persons as contact person, in this case name would be duplicated, and that person could also be a natural person
contacts: {
  shape: sql_table
  id: int {constraint: primary_key}
  name: text
  legal_id: text {constraint: NULL} # required if type is 'legalPerson', optional otherwise. Must be unique, but nulls are considered different
  legal_id_type: text {constraint: NULL} # 'ci' or 'rif', required and set to 'rif' if type is 'legalPerson', optional otherwise
  type: text # 'naturalPerson', 'contactPerson' or 'legalPerson'
  status: text # 'active' or 'deleted', must be 'active' by default
  deleted_at: timestamp {constraint: NULL} # value computed on contact status changed to 'deleted'
}

#* For anyone checking, yes, persons is correct in this context, people is not used as a plural for person in legal/business contexts.
natural_persons: {
  shape: sql_table
  id: int {constraint: [primary_key; foreign_key]}
  email: text {constraint: NULL} # must be unique, but nulls are considered different
  telephone_number: text {constraint: unique} # E164 format
  address: text {constraint: NULL}
}

natural_persons.id -> contacts.id

legal_persons: {
  shape: sql_table
  id: int {constraint: [primary_key; foreign_key]}
}

legal_persons.id -> contacts.id

contact_persons: {
  shape: sql_table
  id: int {constraint: [primary_key; foreign_key]}
  work_email: text {constraint: NULL} # must be unique, but nulls are considered different
  work_telephone_number: text {constraint: unique} # E164 format
  role: text {constraint: NULL}
  legal_person_id: int {constraint: foreign_key}
}

contact_persons.id -> contacts.id
contact_persons.legal_person_id -> legal_persons.id 

channels: {
  shape: sql_table
  id: int {constraint: primary_key}
}

# Following statuses should be created by default: 'Vigente', 'Cotización', 'Negociación', 'Cierre'
sale_cycle_pipeline_statuses: {
  shape: sql_table
  id: int {constraint: primary_key}
  name: text
  order: int {constraint: unique}
  color: text {constraint: unique} # hex string, like #808080
  card_color: text {constraint: unique} # hex string, like #c4c0c0
}

sale_cycle_types: {
  shape: sql_table
  id: int {constraint: primary_key}
  name: text
  slug: text {constraint: unique}
  color: text {constraint: unique} # hex string, like #808080
  status: text # 'active' or 'deleted'. Must be 'active' by default
  deleted_at: timestamp {constraint: NULL} # value computed on status changed to 'deleted'
}

sale_cycles: {
  shape: sql_table
  id: int {constraint: primary_key}
  summary: text {constraint: NULL} # should be short, need to validate how many characters. Only null on creation, can't be explicitly set to null on following updates
  description: text {constraint: NULL} # plain text or rich text? Only null on creation, can't be explicitly set to null on following updates
  priority: text # 'high', 'medium' or 'low'. Defaults to 'medium' on creation
  status: text # 'open', 'won' or 'lost', 'won' and 'lost' are both implicitly 'closed'. Must be 'open' by default
  lead_id: int {constraint: foreign_key}
  channel_id: int {constraint: foreign_key}
  seller_id: int {constraint: foreign_key}
  pipeline_status_id: int {constraint: foreign_key} # defaults to pipeline status with smallest order on creation
  city_id: int {constraint: foreign_key}
  state_id: int {constraint: foreign_key}
  type_id: int {constraint: foreign_key}
}

sale_cycles.city_id -> cities.id
sale_cycles.state_id -> cities.state_id
sale_cycles.type_id -> sale_cycle_types.id
sale_cycles.lead_id -> contacts.id # leads can only be contacts of type 'naturalPerson' or 'contactPerson', excluding 'legalPerson'
sale_cycles.seller_id -> sellers.id
sale_cycles.pipeline_status_id -> sale_cycle_pipeline_statuses.id
sale_cycles.channel_id -> channels.id

lost_sale_cycles: {
  shape: sql_table
  id: int {constraint: [primary_key; foreign_key]}
  reason: text
  lost_at: timestamp # value computed on sale cycle status changed to 'lost'
}

lost_sale_cycles.id -> sale_cycles.id

won_sale_cycles: {
  shape: sql_table
  id: int {constraint: [primary_key; foreign_key]}
  winnning_quotation_id: int {constraint: [foreign_key; unique]}
  won_at: timestamp # value computed on sale cycle status changed to 'won'
}

won_sale_cycles.id -> sale_cycles.id
won_sale_cycles.winning_quotation_id -> quotations.id

sale_cycle_notes: {
  shape: sql_table
  id: int {constraint: primary_key}
  text: text # plain text or rich text?
  sale_cycle_id: int {constraint: foreign_key}
  user_id: int {constraint: foreign_key}
}

sale_cycle_notes.sale_cycle_id -> sale_cycles.id
sale_cycle_notes.user_id -> users.id # only users of type 'director', 'manager' or 'seller' can leave notes on sale cycles

quotations: {
  shape: sql_table
  id: int {constraint: primary_key}
  code: text {constraint: unique} # same format as previous implementation: first letter of seller name, sequential based on amount of quotations of that seller, '-', last two digits of year, first two letters of channel description, all uppercased
  terms_and_conditions: text
  iva: numeric {constraint: NULL}
  igtf: numeric {constraint: NULL} # may only be set if iva is set
  shipping_fee: numeric {constraint: NULL}
  installation_fee: numeric {constraint: NULL}
  status: text # 'active' or 'deleted'. Must be 'active' by default
  deleted_at: timestamp {constraint: NULL} # value computed on quotation status changed to 'deleted'
  sale_cycle_id: int {constraint: foreign_key}
}

quotations.sale_cycle_id -> sale_cycles.id

quotation_elements: {
  shape: sql_table
  id: integer {constraint: [primary_key]}
  description: text
  price: numeric
  quantity: integer
  type: text # 'product' or 'combo'
  quotation_id: integer {constraint: [foreign_key]}
}

quotation_elements.quotation_id -> quotations.id

quotation_products: {
  shape: sql_table
  id: integer {constraint: [primary_key; foreign_key]}
  product_id: integer {constraint: [foreign_key]}
}

quotation_products.id -> quotation_elements.id
quotation_products.product_id -> products.id

quotation_combos: {
  shape: sql_table
  id: integer {constraint: [primary_key; foreign_key]}
}

quotation_combos.id -> quotation_elements.id

quotation_combo_products: {
  shape: sql_table
  product_id: integer {constraint: [primary_key; foreign_key]}
  combo_id: integer {constraint: [primary_key; foreign_key]}
  quantity: integer
}

quotation_combo_products.combo_id -> quotation_combos.id
quotation_combo_products.product_id -> products.id

tasks: {
  shape: sql_table
  id: int {constraint: primary_key}
  description: text
  type: text # 'follow-up', 'meeting', 'review'
  status: text # 'pending', 'completed', 'expired', 'deleted'. 'pending' by default
  deadline: timestamp
  sale_cycle_id: int {constraint: foreign_key}
}

tasks.sale_cycle_id -> sale_cycles.id