# Conceptos/Bases teóricas
vars: {
  d2-config: {
    layout-engine: elk
    sketch: true
  }
}
direction: up

programming: Programación {
  shape: rectangle
}

hci: Interacción Humano-Computador (HCI) {
  shape: rectangle
}

programming-paradigms: Paradigmas de programación {
  shape: rectangle
}

imperative-programming: Programación imperativa {
  shape: rectangle
}

control-flow: Control flow {
  shape: rectangle
}

declarative-programming: Programación declarativa {
  shape: rectangle
}

programming-ambient: Ambiente de programación/Entorno de desarrollo {
  shape: rectangle
}

ide: Entorno de desarrollo integrado (IDE) {
  shape: rectangle
}

programming-language: Lenguaje de programación {
  shape: rectangle
}

tangible-programming: Programación tangible {
  shape: rectangle
}

tangible-programming-language: Lenguaje de programación tangible {
  shape: rectangle
}

spatial-augmented-reality: Realidad aumentada espacial {
  shape: rectangle
}

kids-6-to-9: Niños de 6 a 9 años {
  shape: rectangle
}

programming-for-kids: Programación para niños {
  shape: rectangle
}

computational-thinking: Pensamiento computacional {
  shape: rectangle
}

media-use-in-children: Uso de medios digitales en niños {
  shape: rectangle
}

tangible-user-interfaces: Interfaces de usuario tangibles (TUIs) {
  shape: rectangle
}

tui-types: Tipos de TUIs {
  shape: rectangle
}

tabletop-tui: Superficies interactivas (TUIs de mesa) {
  shape: rectangle
}

computational-thinking-unplugged: Pensamiento computacional desenchufado {
  shape: rectangle
}

merrills-principles-of-instruction: Principios de instrucción de Merrill {
  shape: rectangle
}

constructionism: Construccionismo {
  shape: rectangle
}

constructivism: Constructivismo {
  shape: rectangle
}

collaborative-learning: Aprendizaje colaborativo {
  shape: rectangle
}

significant-learning: Aprendizaje significativo {
  shape: rectangle
}

learning-theories: Teorías del aprendizaje {
  shape: rectangle
}

dataflow: Dataflow {
  shape: rectangle
}

dataflow-programming: Programación dataflow {
  shape: rectangle
}

dataflow-programming-language: Lenguaje de programación dataflow {
  shape: rectangle
}

thesis: Ambiente de Programación Tangible con Realidad Aumentada Espacial Orientado a Niños entre 6 y 9 años {
  shape: rectangle
}

programming-paradigms -- programming

imperative-programming -- programming-paradigms

control-flow -- imperative-programming

declarative-programming -- programming-paradigms

dataflow -- dataflow-programming

dataflow-programming -- programming-paradigms

dataflow-programming-language -- programming-language

programming-ambient -- programming
programming-ambient -- thesis

ide -- programming-ambient

programming-language -- programming

tangible-programming -- programming
tangible-programming -- thesis

computational-thinking -- computational-thinking-unplugged
computational-thinking -- thesis

computational-thinking-unplugged -- merrills-principles-of-instruction
# computational-thinking -- programming-for-kids
# computational-thinking -- tangible-programming

# programming-for-kids -- tangible-programming
programming-for-kids -- programming
programming-for-kids -- media-use-in-children
programming-for-kids -- constructionism
programming-for-kids -- kids-6-to-9

constructionism -- learning-theories
constructionism -- constructivism
constructionism -- collaborative-learning

constructivism -- learning-theories

collaborative-learning -- learning-theories

kids-6-to-9 -- thesis

tangible-user-interfaces -- tangible-programming
tangible-user-interfaces -- spatial-augmented-reality

tui-types -- tangible-user-interfaces

tabletop-tui -- tui-types

hci -- tangible-user-interfaces

spatial-augmented-reality -- thesis

tangible-programming-language -- programming-language
