# Conceptos/Bases teóricas

programming: Programación {
  shape: rectangle
}

programming-ambient: Ambiente de programación {
  shape: rectangle
}

programming-language: Lenguaje de programación {
  shape: rectangle
}

tangible-programming: Programación tangible {
  shape: rectangle
}

spatial-augmented-reality: Realidad aumentada espacial {
  shape: rectangle
}

kids-6-to-9: Niños de 6 a 9 años {
  shape: rectangle
}

programming-for-kids: Programación para niños {
  shape: rectangle
}

computational-thinking: Pensamiento computacional {
  shape: rectangle
}

media-use-in-children: Uso de medios digitales en niños {
  shape: rectangle
}

tangible-user-interfaces: Interfaces de usuario tangibles {
  shape: rectangle
}

computational-thinking-unplugged: Pensamiento computacional desenchufado {
  shape: rectangle
}

merrills-principles-of-instruction: Principios de instrucción de Merrill {
  shape: rectangle
}

constructionism: Construccionismo {
  shape: rectangle
}

dataflow: Dataflow {
  shape: rectangle
}

control-flow: Control flow {
  shape: rectangle
}

dataflow-programming-language: Lenguaje de programación dataflow {
  shape: rectangle
}

programming-ambient -- programming

tangible-programming -- programming

programming-language -- programming

computational-thinking -- programming
computational-thinking -- programming-for-kids
# computational-thinking -- tangible-programming
computational-thinking -- computational-thinking-unplugged
computational-thinking -- merrills-principles-of-instruction

# programming-for-kids -- tangible-programming
programming-for-kids -- programming
programming-for-kids -- media-use-in-children
programming-for-kids -- constructionism
programming-for-kids -- kids-6-to-9

tangible-user-interfaces -- tangible-programming
tangible-user-interfaces -- spatial-augmented-reality
