// Bases Teóricas
// Ambiente de Programación Tangible con Realidad Aumentada Espacial
// Orientado a Niños entre 6 y 9 años

== Bases Teóricas

== Desarrollo Cognitivo y Aprendizaje en Niños de 6 a 9 Años

Según la teoría de desarrollo cognitivo de Piaget ~cita requerida~, existen cuatro etapas principales en el desarrollo cognitivo: la etapa sensorio-motora, que va desde el nacimiento hasta aproximadamente los dos años, y donde el conocimiento se obtiene mediante la interacción física con el entorno inmediato; la etapa preoperacional, aproximadamente entre los dos y siete años, caracterizada por el egocentrismo y la dificultad para realizar operaciones mentales complejas, aunque ya se comienza a ganar la capacidad de utilizar objetos simbólicos y adoptar roles ficticios; la etapa de las operaciones concretas, aproximadamente entre los siete y doce años, en la que se empieza a usar la lógica para llegar a conclusiones válidas con situaciones concretas y los sistemas de categorías se vuelven más complejos; y, finalmente, la etapa de las operaciones formales, desde los doce años en adelante, donde se desarrolla la capacidad para utilizar la lógica con conceptos abstractos y el razonamiento hipotético-deductivo.

La etapa de desarrollo cognitivo que corresponde a niños entre 6 y 9 años se encuentra en una transición crucial: a los 6 años aún están en la etapa preoperacional, donde el egocentrismo sigue presente y el pensamiento mágico basado en asociaciones simples predomina; sin embargo, alrededor de los 7 años, acceden a la etapa de las operaciones concretas, donde comienzan a usar la lógica para situaciones concretas y el egocentrismo disminuye notablemente. Esta transición marca un período fundamental de desarrollo donde los niños empiezan a manipular información lógicamente, siendo capaces de realizar operaciones mentales sobre objetos concretos, pero aún tienen limitaciones para trabajar con conceptos abstractos puros. Esta característica es fundamental para el diseño de ambientes de programación tangible, ya que la manipulación física de objetos permite a los niños comprender conceptos abstractos de programación a través de la experiencia concreta. El aprendizaje mediante la manipulación física de objetos, también conocido como aprendizaje kinestésico ~cita requerida~, ha demostrado ser especialmente efectivo en niños de edades tempranas ~cita requerida, podría ser de Zapata-Ros~. La interacción con objetos tangibles permite que los niños comprendan conceptos abstractos mediante la experiencia sensorial y motora, facilitando la internalización de conocimientos complejos.

El constructivismo de Piaget ~cita requerida~ postula que el conocimiento se construye activamente a través de la interacción entre el individuo y su entorno, mediante procesos de asimilación y acomodación. Según esta perspectiva, los niños no son receptores pasivos de información, sino que construyen activamente su comprensión del mundo a partir de sus experiencias y estructuras cognitivas preexistentes. El aprendizaje ocurre cuando los niños interactúan con el entorno y reorganizan sus esquemas mentales para incorporar nueva información. Papert (1980) propuso el construccionismo como una extensión y evolución del constructivismo de Piaget ~revisar bien si Papert lo propone así, creo que sí~, enfatizando que el aprendizaje es significativamente más efectivo cuando los estudiantes no solo construyen conocimiento mentalmente, sino que construyen objetos tangibles o digitales concretos que pueden ser compartidos, discutidos, observados y refinados con otros. El construccionismo sugiere que el aprendizaje ocurre de manera más significativa cuando los estudiantes están activamente involucrados en la construcción de algo externo y compartible, estableciendo un ciclo de reflexión-acción-reflexión donde el objeto construido sirve como vehículo para pensar y aprender. Esta perspectiva se alinea perfectamente con el enfoque de programación tangible ~cita requerida~, donde los niños construyen programas físicos que pueden ser ejecutados, observados, modificados y compartidos, creando una experiencia de aprendizaje profunda y significativa que trasciende la mera transmisión de conceptos.

== Pensamiento Computacional en Edades Tempranas

Wing (2006, 2011) ~revisar si se puede citar de esta forma, además, añadir artículo del 2008~ define el pensamiento computacional como un conjunto de habilidades que incluyen la formulación de problemas de manera que permita el uso de computadoras para resolverlos, la organización y análisis lógico de información, la representación mediante abstracciones, y la búsqueda de soluciones efectivas. Para niños de 6 a 9 años ~añadir cita a Sánchez Vera 2019 e información sobre su artículo~, estos componentes deben ser adaptados a su nivel de desarrollo cognitivo, utilizando representaciones concretas y manipulables. El desarrollo del pensamiento computacional en niños requiere de estrategias pedagógicas específicas que consideren las limitaciones cognitivas propias de la edad. La programación tangible emerge como una estrategia efectiva ~añadir cita a Sánchez Vera 2019 e información sobre su artículo~, ya que permite a los niños experimentar con conceptos computacionales sin requerir habilidades de lectura avanzadas o conocimiento previo de sintaxis de lenguajes de programación tradicionales.

La sociedad contemporánea ~¿no sería digital?~ demanda profesionales cualificados en industrias tecnológicas, lo que ha llevado a reconocer la necesidad del pensamiento computacional, que, para Zapata-Ros (2025), es una nueva alfabetización: ~revisar esto~ la alfabetización digital. Como cualquier alfabetización fundamental, debe iniciarse desde las primeras etapas del desarrollo individual. Sin embargo, las competencias de codificación son la parte más visible de una forma de pensar que trasciende el ámbito de la programación: existe una forma específica de organizar ideas y representaciones que favorece las competencias computacionales, y puede ser desarrollada mediante actividades y entornos de aprendizaje apropiados desde edades tempranas ~parafrasear esto de otra forma~.

Zapata-Ros (2019) propone el pensamiento computacional desenchufado como un enfoque que permite a los niños desarrollar competencias computacionales sin el uso de pantallas o computadoras. Las actividades desenchufadas preparan a los niños para conceptos que serán evocados en ciclos superiores de aprendizaje, estableciendo una base sólida que facilitará la transición hacia herramientas más avanzadas cuando estén cognitivamente preparados. Este enfoque se basa en los principios fundamentales de la instrucción propuestos por Merrill (2002) ~revisar fecha~, que incluyen:

- *Enfoque centrado en tareas o problemas*: Diseño de instrucción alrededor de problemas auténticos del mundo real que los aprendices probablemente encontrarán, fomentando la participación activa en actividades de resolución de problemas.

- *Activación*: Se enfoca en involucrar los conocimientos previos y experiencias de los aprendices para crear una base para el nuevo aprendizaje. Implica estimular la curiosidad, presentar ejemplos del mundo real y conectar nueva información con conocimientos existentes.

- *Demostración*: Proporcionar modelos o ejemplos claros que ilustren los resultados de aprendizaje deseados, permitiendo que los aprendices observen actuaciones de expertos, simulaciones o estudios de caso para desarrollar comprensión.

- *Aplicación*: Ofrecer oportunidades para que los aprendices practiquen y apliquen sus conocimientos y habilidades en contextos auténticos, requiriendo que resuelvan problemas, tomen decisiones y se involucren en tareas realistas.

- *Integración*: Promover la transferencia de conocimientos y habilidades a nuevas situaciones, proporcionando oportunidades para conectar el aprendizaje con contextos del mundo real y aplicarlo de manera significativa.

El principio de activación es particularmente crucial para este trabajo, ya que este permite construir sobre experiencias previas con objetos físicos, juegos y manipulaciones concretas que los niños ya comprenden. Al activar conocimientos previos sobre manipulación de objetos, secuencias de acciones y relaciones causa-efecto que los niños han experimentado en sus actividades cotidianas, se establece un puente cognitivo fundamental que facilita la transición hacia conceptos computacionales abstractos a través de la experiencia concreta, haciendo que el aprendizaje sea más accesible y significativo.

Los principios fundamentales de instrucción, se integran dentro del marco más amplio del diseño instruccional ~cita requerida~, que se refiere al proceso sistemático de planificar, desarrollar, implementar y evaluar experiencias de aprendizaje efectivas. Este campo interdisciplinario ~cita requerida, tengo un artículo que habla sobre esto y específicamente en el caso del constructivismo y el construccionismo~ combina teorías de aprendizaje, metodologías pedagógicas y principios de diseño para crear entornos educativos que faciliten la adquisición de conocimientos y habilidades. El diseño instruccional implica la identificación de objetivos de aprendizaje, la selección de estrategias pedagógicas apropiadas, la organización de contenido, y el diseño de actividades y evaluaciones que promuevan el aprendizaje significativo ~revisar muy bien esto y ver si se refiere a ese significativo, al de Papert, o al del otro autor~. También se derivan las estrategias didácticas, que son los métodos y técnicas específicos que se emplean para facilitar el proceso de enseñanza-aprendizaje ~cita requerida~. Estas estrategias se adaptan según el contexto, los objetivos de aprendizaje y las características de los aprendices. Las estrategias didácticas se diseñan intencionalmente para alinearse con los principios de instrucción y maximizar la efectividad del proceso educativo ~revisar, quizás sería mejor decir que pueden diseñarse para alinearse con los principios de instrucción~, especialmente cuando se trata de conceptos abstractos que deben ser comprendidos a través de manipulaciones concretas.


== Teoría del aprendizaje

La teoría del aprendizaje proporciona el marco conceptual fundamental para comprender cómo los individuos adquieren, procesan y retienen conocimiento ~cita requerida, y debería ser teorías del aprendizaje~. El aprendizaje puede entenderse ~cita requerida~ como un proceso activo de construcción de conocimiento que ocurre a través de la interacción entre el individuo y su entorno. Diversas perspectivas teóricas han contribuido a la comprensión de este proceso complejo: el conductismo enfatiza la modificación de comportamientos mediante estímulos y refuerzos, el cognitivismo se centra en los procesos mentales internos y la organización del conocimiento, mientras que el constructivismo postula que el conocimiento se construye activamente mediante la experiencia y la interacción con el entorno.

El aprendizaje colaborativo ~cita requerida~ se fundamenta en teorías socioconstructivistas que enfatizan el papel de la interacción social en el aprendizaje. La colaboración permite que los niños aprendan de sus pares, desarrollen habilidades de comunicación, y construyan conocimiento colectivamente mediante la discusión y negociación de significados. El aprendizaje colaborativo en niños promueve el desarrollo de habilidades sociales, mejora la comprensión mediante la explicación a otros, fomenta el pensamiento crítico a través de la discusión, y desarrolla habilidades de trabajo en equipo. Estos beneficios son especialmente importantes en el contexto de la programación, donde la colaboración es una práctica común en entornos profesionales ~cita requerida? Idk, no creo, pero igual dejo la anotación~.

En el contexto educativo, la selección y diseño de recursos, materiales y medios didácticos adecuados es fundamental para facilitar el proceso de aprendizaje ~cita requerida~. Estos elementos constituyen herramientas estratégicas que, cuando se diseñan y utilizan apropiadamente, pueden potenciar significativamente la efectividad del proceso educativo.

Un recurso didáctico ~cita requerida~ es un elemento más amplio y general que incluye cualquier elemento, estrategia o herramienta que puede ser utilizada con fines educativos. Los recursos didácticos abarcan desde objetos físicos hasta estrategias metodológicas, entornos, personas y experiencias que pueden contribuir al proceso de enseñanza-aprendizaje. Son elementos flexibles que pueden ser adaptados y reutilizados en diferentes contextos educativos.

Un material didáctico ~cita requerida~ es un recurso didáctico específico y concreto, generalmente físico o digital, que ha sido diseñado intencionalmente con un propósito educativo explícito. Los materiales didácticos son objetos tangibles o digitales que contienen información estructurada y organizada para facilitar el aprendizaje. Poseen características específicas como objetivos de aprendizaje definidos, contenidos organizados pedagógicamente, y diseño que facilita su uso educativo.

Un medio didáctico ~cita requerida~ se refiere al canal o vía a través del cual se transmite y presenta la información educativa. Los medios didácticos son los soportes o tecnologías que vehiculan el contenido educativo, determinando cómo se presenta la información al aprendiz. Diferentes medios (visual, auditivo, táctil, kinestésico) activan diferentes canales sensoriales y cognitivos, influyendo en cómo se procesa y retiene la información. La realidad aumentada espacial, por ejemplo, ~puede~ constituye un medio didáctico que presenta información visual superpuesta sobre el mundo físico, activando canales visuales y espaciales para facilitar la comprensión de conceptos abstractos mediante representaciones visuales concretas.


== Programación y Entornos de Desarrollo

Los entornos de desarrollo constituyen el conjunto de herramientas, bibliotecas y configuraciones que facilitan la creación, edición, depuración y ejecución de programas computacionales ~cita requerida~. Entre estos entornos, los Entornos de Desarrollo Integrados (IDE) representan aplicaciones que combinan múltiples herramientas de desarrollo en una interfaz unificada, incluyendo editores de código con resaltado de sintaxis, depuradores, compiladores, sistemas de control de versiones y gestores de proyectos ~cita requerida~. La programación es el proceso de diseñar y construir programas computacionales que ejecutan tareas específicas mediante la escritura de código en lenguajes de programación. Cuando se trata de programación para niños, especialmente en edades tempranas, es necesario adaptar estos entornos a las capacidades cognitivas y motoras de los aprendices. Las tecnologías educativas, entendidas como el conjunto de herramientas, recursos y metodologías que integran tecnología digital en procesos de enseñanza-aprendizaje, han demostrado ser efectivas para facilitar el aprendizaje cuando se diseñan apropiadamente. El uso de medios digitales en niños requiere consideraciones especiales: mientras que los medios digitales pueden ofrecer interactividad, retroalimentación inmediata y representaciones visuales atractivas, también presentan desafíos relacionados con la atención, la sobrecarga cognitiva y la necesidad de mantener el equilibrio entre la estimulación digital y el desarrollo de habilidades físicas y sociales. La programación para niños debe considerar diferentes paradigmas de programación, que son estilos o enfoques fundamentales para estructurar y organizar código.

Un lenguaje de programación es un sistema formal de comunicación que permite a los programadores expresar instrucciones y algoritmos de manera estructurada para que sean ejecutados por una computadora. Los lenguajes de programación proporcionan un conjunto de reglas sintácticas y semánticas que definen cómo se pueden combinar símbolos y palabras clave para crear programas funcionales. Los paradigmas de programación representan estilos o enfoques fundamentales para estructurar y organizar código, definiendo la forma en que los programadores conceptualizan y resuelven problemas computacionales. El paradigma imperativo es uno de los paradigmas más fundamentales, donde los programas se estructuran como secuencias de instrucciones que modifican el estado del programa mediante asignaciones y comandos. En este paradigma, el programador especifica explícitamente los pasos que la computadora debe seguir para resolver un problema, controlando el flujo de ejecución mediante estructuras de control como bucles y condicionales.
El dataflow es un paradigma de programación donde el flujo de datos determina la ejecución del programa, en lugar de un flujo de control secuencial. En este paradigma, las operaciones se ejecutan cuando sus datos de entrada están disponibles, creando un modelo de programación basado en la transformación y el flujo de información a través de una red de operaciones.

El lenguaje de programación tangible es un enfoque donde los elementos del lenguaje de programación se representan mediante objetos físicos manipulables, permitiendo a los usuarios construir programas mediante la organización espacial y física de estos objetos, eliminando la necesidad de sintaxis textual y facilitando la comprensión de conceptos computacionales a través de la manipulación concreta.

== Programación Tangible

La programación tangible se basa en el concepto de interfaces tangibles de usuario (TUI), donde los usuarios interactúan con sistemas computacionales mediante la manipulación de objetos físicos. En el contexto de la programación, cada objeto físico representa un comando o estructura de control, permitiendo a los usuarios construir programas mediante la organización física de estos objetos. La programación tangible tiene sus raíces en trabajos pioneros como TORTIS de Perlman (1974-1976) y AlgoBlock de Suzuki y Kato (1993). Estos sistemas demostraron que los niños pueden aprender conceptos de programación mediante la manipulación de objetos físicos, estableciendo los principios fundamentales que guían el diseño de sistemas de programación tangible contemporáneos.

Suzuki y Kato (1993) identificaron principios clave para el diseño de ambientes de programación tangible colaborativos: facilidad de uso, acceso simultáneo, monitoreo mutuo y pase del turno mediante gestos. Estos principios fomentan la conversación y colaboración entre participantes, aspectos esenciales para el aprendizaje colaborativo. La programación tangible ofrece varios beneficios pedagógicos: reduce la barrera de entrada al eliminar la necesidad de sintaxis textual, permite la visualización espacial de estructuras de control, facilita la colaboración mediante el acceso simultáneo a objetos físicos, y proporciona retroalimentación inmediata mediante la ejecución del programa construido. Estos beneficios hacen que la programación tangible sea especialmente adecuada para niños en la etapa operacional concreta, donde la manipulación física facilita la comprensión de conceptos abstractos. La integración de tecnologías de visualización que permitan superponer información virtual directamente sobre los objetos físicos puede potenciar estos beneficios, facilitando la retroalimentación visual inmediata y la comprensión de las relaciones entre los elementos del programa sin interrumpir la interacción directa con el espacio físico.

Park et al. (2015) definen la realidad aumentada espacial como una tecnología que superpone contenido virtual sobre el mundo real mediante proyección directa sobre superficies físicas, a diferencia de la realidad aumentada tradicional que requiere dispositivos intermediarios como pantallas. Esta tecnología permite la interacción directa con el espacio físico, que se refleja en el espacio virtual. La realidad aumentada espacial se diferencia de la realidad aumentada tradicional en que no requiere dispositivos intermediarios (como tablets o smartphones) para visualizar el contenido aumentado.



